### ISSUE TITLE
#35 As a User, I want to be able to see the 'Create' and 'View' buttons in a position that feels natural.

### ISSUE THREAD

**Issue by SymbiodRelations** [Access-Point-Program/cohort-3-rules-engine-admin#62]
- As a User, I want to easily see a 'Create' button and a 'View' button.
- As a User, I want the buttons to be easy to navigate to (for example: If I push a button in the top-center of the screen on the previous page/render, I don't want my next button to be on the bottom-right).

**Comment by Dajoun1** [comment]
This is not apart of our application, the dashboard team has to create the create & view button.
